<?php

namespace ContainerPWK60re;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingTextResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RatingTextResponse' shared autowired service.
     *
     * @return \App\Service\RatingTextResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RatingTextResponse.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\RatingTextResponse'])) {
            return $container->privates['App\\Service\\RatingTextResponse'];
        }

        return $container->privates['App\\Service\\RatingTextResponse'] = new \App\Service\RatingTextResponse($a);
    }
}
