nelmio_api_doc:
    documentation:
        info:
            title: Movie Review
            description: Movie Review Website
            version: 1.0.0
        servers:
            - url: https://127.0.0.1:8000/
              description: API over HTTPS
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/docs$) # Accepts routes under /api except /api/doc