<?php

namespace ContainerPqESzBL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZthF74TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZthF74T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZthF74T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::userRoles' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController::createMovie' => ['privates', '.service_locator.fNvIwJr', 'get_ServiceLocator_FNvIwJrService', true],
            'App\\Controller\\DefaultController::createRating' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\DefaultController::createReport' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\DefaultController::createReview' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\DefaultController::movies' => ['privates', '.service_locator.qWVjwJm', 'get_ServiceLocator_QWVjwJmService', true],
            'App\\Controller\\DefaultController::viewMovie' => ['privates', '.service_locator.qWVjwJm', 'get_ServiceLocator_QWVjwJmService', true],
            'App\\Controller\\DefaultController::viewReview' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController::viewReviewReview' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ModController::reportedReviews' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModController::review' => ['privates', '.service_locator.qWVjwJm', 'get_ServiceLocator_QWVjwJmService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:userRoles' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController:createMovie' => ['privates', '.service_locator.fNvIwJr', 'get_ServiceLocator_FNvIwJrService', true],
            'App\\Controller\\DefaultController:createRating' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\DefaultController:createReport' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\DefaultController:createReview' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\DefaultController:movies' => ['privates', '.service_locator.qWVjwJm', 'get_ServiceLocator_QWVjwJmService', true],
            'App\\Controller\\DefaultController:viewMovie' => ['privates', '.service_locator.qWVjwJm', 'get_ServiceLocator_QWVjwJmService', true],
            'App\\Controller\\DefaultController:viewReview' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController:viewReviewReview' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ModController:reportedReviews' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModController:review' => ['privates', '.service_locator.qWVjwJm', 'get_ServiceLocator_QWVjwJmService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::userRoles' => '?',
            'App\\Controller\\DefaultController::createMovie' => '?',
            'App\\Controller\\DefaultController::createRating' => '?',
            'App\\Controller\\DefaultController::createReport' => '?',
            'App\\Controller\\DefaultController::createReview' => '?',
            'App\\Controller\\DefaultController::movies' => '?',
            'App\\Controller\\DefaultController::viewMovie' => '?',
            'App\\Controller\\DefaultController::viewReview' => '?',
            'App\\Controller\\DefaultController::viewReviewReview' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\ModController::reportedReviews' => '?',
            'App\\Controller\\ModController::review' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:userRoles' => '?',
            'App\\Controller\\DefaultController:createMovie' => '?',
            'App\\Controller\\DefaultController:createRating' => '?',
            'App\\Controller\\DefaultController:createReport' => '?',
            'App\\Controller\\DefaultController:createReview' => '?',
            'App\\Controller\\DefaultController:movies' => '?',
            'App\\Controller\\DefaultController:viewMovie' => '?',
            'App\\Controller\\DefaultController:viewReview' => '?',
            'App\\Controller\\DefaultController:viewReviewReview' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\ModController:reportedReviews' => '?',
            'App\\Controller\\ModController:review' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
