<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Review extends \App\Entity\Review implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'author' => [parent::class, 'author', null],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'movie' => [parent::class, 'movie', null],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null],
        "\0".parent::class."\0".'reports' => [parent::class, 'reports', null],
        "\0".parent::class."\0".'reviewRatings' => [parent::class, 'reviewRatings', null],
        'author' => [parent::class, 'author', null],
        'comment' => [parent::class, 'comment', null],
        'id' => [parent::class, 'id', null],
        'movie' => [parent::class, 'movie', null],
        'rating' => [parent::class, 'rating', null],
        'reports' => [parent::class, 'reports', null],
        'reviewRatings' => [parent::class, 'reviewRatings', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
