<?php

namespace ContainerW7mbEPy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QWVjwJmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qWVjwJm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qWVjwJm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ratingTextResponse' => ['privates', 'App\\Service\\RatingTextResponse', 'getRatingTextResponseService', true],
        ], [
            'entityManager' => '?',
            'ratingTextResponse' => 'App\\Service\\RatingTextResponse',
        ]);
    }
}
