<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW7mbEPy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW7mbEPy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW7mbEPy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW7mbEPy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW7mbEPy\App_KernelDevDebugContainer([
    'container.build_hash' => 'W7mbEPy',
    'container.build_id' => 'a4e4e392',
    'container.build_time' => 1699369700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW7mbEPy');
