<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWK60re\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWK60re/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPWK60re.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPWK60re\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPWK60re\App_KernelDevDebugContainer([
    'container.build_hash' => 'PWK60re',
    'container.build_id' => 'd98ffc48',
    'container.build_time' => 1699526460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWK60re');
