<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV62AtQE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV62AtQE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV62AtQE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV62AtQE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV62AtQE\App_KernelDevDebugContainer([
    'container.build_hash' => 'V62AtQE',
    'container.build_id' => '379981ac',
    'container.build_time' => 1699287022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV62AtQE');
