<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'admin_index' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin/index']], [], [], []],
    'user-roles' => [[], ['_controller' => 'App\\Controller\\AdminController::userRoles'], [], [['text', '/admin/user_roles']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'reviews' => [[], ['_controller' => 'App\\Controller\\DefaultController::reviews'], [], [['text', '/reviews']], [], [], []],
    'create-movie' => [[], ['_controller' => 'App\\Controller\\DefaultController::createMovie'], [], [['text', '/movie/create']], [], [], []],
    'create-review' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::createReview'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/movie/review/create']], [], [], []],
    'create-review-review' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::createReviewReview'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/movie/review/rate/create']], [], [], []],
    'view-movie' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::viewMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/movie/view']], [], [], []],
    'view-review' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::viewReview'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/review/view']], [], [], []],
    'view-review-review' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::viewReviewReview'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/review/view_rating']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'mod_index' => [[], ['_controller' => 'App\\Controller\\ModController::index'], [], [['text', '/mod/index']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
];
